### ISSUE TITLE
Adding a suitable favicon 

### ISSUE THREAD

**Issue by pulkithanda** [pulkithanda/Portfolio-hf#1]
<h2 align="center">Adding a suitable favicon to the website using HTML </h2>
<div align="center">
<p> Adding a suitable favicon to the template website using HTML </p>
<img src="https://cdn.discordapp.com/attachments/789454958453063702/893822932185399306/unknown.png" height="50px">
<p> For further Issues contact below or use my discord to contact me <i>Alphabet# 0352</i> </p>

**Comment by trybick** [comment]
I can pick this up 👋

**Comment by Hussain6** [comment]
Can you assign this to me?

**Comment by pulkithanda** [comment]
It's a portfolio website the Minecraft gif I have to change. Find a suitable favicon, please. 
Assigned it to both of you, whichever of you send a valid PR first ill merge it and label another one as hacktoberfest-accepted.
(btw if it helped you, please consider following me and starring the repository, thanks!)

**Comment by trybick** [comment]
Sure, no problem. The PR #2 has been updated with new icon.

**Comment by agrajagrawal** [comment]
@pulkithanda Hey I have also added a Favicon that matches your theme!

**Comment by pulkithanda** [comment]
okk then thank you @trybick and @agrajagrawal for contributing. I'll be merging one PR and labeling the other as "hacktoberfest-accepted" so both of your purposes gets solved. By the way, where do you find such SVG's?

**Comment by Hussain6** [comment]
I have changed the favicon and the profile image. Check it out and kindly add the hacktoberfest label.

**Comment by trybick** [comment]
> By the way, where do you find such SVG's?

I use https://icons8.com/


> I have changed the favicon and the profile image. Check it out and kindly add the hacktoberfest label.

**Comment by npkeerthi** [comment]
@pulkithanda  Is this still open 
If so, May I work for it

**Comment by pulkithanda** [comment]
> @pulkithanda Is this still open If so, May I work for it

It's completed mate. Thanks for the offer though.
