### ISSUE TITLE
Fix wrong active Page links in blog page

### ISSUE THREAD

**Issue by ExpressHermes** [pulkithanda/Portfolio-hf#8]
On the blog page, the page links (attached image) have set Page 2 as active. It should be set '1' as active and since there are no more blogs, other links should be removed.

<img width="302" alt="Screenshot 2021-10-03 at 12 26 24 PM" src="https://user-images.githubusercontent.com/46123679/135743579-2c08b10a-dfe7-49e2-858e-ef269ec0a264.png">

**Comment by ExpressHermes** [comment]
I can work on this.

**Comment by pulkithanda** [comment]
@ExpressHermes Instead of that you can add the blog articles in 1 3 4 as well.

**Comment by ExpressHermes** [comment]
okay, cool!

**Comment by ExpressHermes** [comment]
@ExpressHermes adding extra blogs that have only placeholder content will bloat the website with unnecessary content. The wrong active link has been fixed in the #18 PR. I think this issue should be closed after merging the #18.

**Comment by ExpressHermes** [comment]
Fixed in #18
