### ISSUE TITLE
Load the content dynamically from a JS/JSON file

### ISSUE THREAD

**Issue by ExpressHermes** [pulkithanda/Portfolio-hf#9]
The portfolio information should be loaded from a JSON/JS file so that anyone can update the whole website by just making changes in one file. This website can be customized to anyone using only one file.

The information that can be in the file in the following format:

```
{
"name": 'John Doe',
"DOB": 01/01/1945,
"address" : "Somewhere cool, Zootopia - 42069",
"email": john.doe@email.com"
"nationality": "Zootopian",
"languages": "All-Tongue, Skrull",
}
```

**Comment by ExpressHermes** [comment]
I can work on this

**Comment by pulkithanda** [comment]
Sure @ExpressHermes Go Ahead. You can work on this.
